/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Display;

import javax.swing.ImageIcon;
import Clases.Conexion;
import Clases.Usuario;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author HENRYTO
 */
public class JLogin extends javax.swing.JFrame {

    /**
     * Creates new form JLogin
     */
    public JLogin() {
        initComponents();
        ImageIcon icono = new ImageIcon("src\\main\\java\\Imagenes\\city.png");
        city.setIcon(icono);
        ImageIcon icono2 = new ImageIcon("src\\main\\java\\Imagenes\\logo.png");
        logo.setIcon(icono2);
        ImageIcon icono3 = new ImageIcon("src\\main\\java\\Imagenes\\NYHLogo.png");
        Logo2.setIcon(icono3);
        setIconImage(new ImageIcon("src\\main\\java\\Imagenes\\NYHLogo.png").getImage());
        SetImageLabel(Logo2, "src\\main\\java\\Imagenes\\NYHLogo.png");
        Dimension displayLogin = Toolkit.getDefaultToolkit().getScreenSize();
        int height = displayLogin.height;
        int width = displayLogin.width;
        setLocation((width - getWidth()) / 2, (height - getHeight()) / 2);
        
     
        
    }
    
    private static void SetImageLabel(JLabel Logo2, String root ){
        ImageIcon image =new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(Logo2.getWidth(), Logo2.getHeight(), Image.SCALE_DEFAULT));
        Logo2.setIcon(icon);
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUsuario1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Password = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        panelIngresar = new javax.swing.JPanel();
        jLabelIngresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 300, 170));

        name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Gestor de Inventarios");
        name.setAlignmentX(0.5F);
        background.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 260, 70));
        background.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 0, 310, 500));

        Logo2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Logo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 100));

        titulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        titulo.setText("INICIAR SESIÓN");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 210, 40));

        usuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        usuario.setText("USUARIO");
        background.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, 20));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario1.setText("Ingrese su nombre de usuario");
        txtUsuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 470, 40));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        Password.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Password.setText("CONTRSEÑA");
        background.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 20));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        background.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 470, 40));

        panelIngresar.setBackground(new java.awt.Color(0, 134, 190));

        jLabelIngresar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIngresar.setText("Ingresar");
        jLabelIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelIngresar.setPreferredSize(new java.awt.Dimension(150, 60));

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarLayout.createSequentialGroup()
                .addComponent(jLabelIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(panelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel background;
    private javax.swing.JLabel city;
    private javax.swing.JLabel jLabelIngresar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panelIngresar;
    private javax.swing.JLabel titulo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
